version: "3.9"

services:
  database:
    image: postgres
    container_name: nlw_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nlw_heat_elixir_dev
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local